# Generated by Django 6.0.2 on 2026-02-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flor',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='flores/'),
        ),
    ]
