# Generated by Django 6.0.2 on 2026-02-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flor', '0002_flor_precio_alter_flor_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flor',
            name='precio',
        ),
    ]
