# Generated by Django 6.0.2 on 2026-03-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flor', '0003_remove_flor_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='flor',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flor',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
